### ISSUE TITLE
Le middleware génère des erreurs lorsqu'il tagge des parcours

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#519]
Erreur visible dans le log:

```
[2022-09-19T16:49:46.362Z] ERROR 1bb6a3dd4564-45/BROKER: MoleculerError: Unable to reach SPARQL endpoint http://fuseki:3030/localData/update. Error message: Bad Request. Query: 
            PREFIX cdlt: <http://virtual-assembly.org/ontologies/cdlt#>
            INSERT { <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie> cdlt:regionOf ?p1 }
            WHERE { BIND(<https://data.lescheminsdelatransition.org/courses/voyage-inaugural-des-chemins-de-la-transition-a-velo> AS ?p1) }
          
    at throw500 (/app/node_modules/@semapps/middlewares/index.js:37:9)
    at Service.fetch (/app/node_modules/@semapps/triplestore/service.js:52:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Service.handler (/app/node_modules/@semapps/triplestore/actions/update.js:30:7)
    at async Service.tag (/app/services/region-tagger.service.js:51:9)
    at async Service.tagCourse (/app/services/region-tagger.service.js:103:11)
    at async Service.ldp.resource.updated (/app/services/region-tagger.service.js:176:11)
    at async Promise.all (index 4) {
  code: 500,
  type: 'INTERNAL_SERVER_ERROR',
  data: { status: 'Server Error', text: 'Unable to reach SPARQL endpoint http://fuseki:3030/localData/update. Error message: Bad Request. Query: \n            PREFIX cdlt: <http://virtual-assembly.org/ontologies/cdlt#>\n            INSERT { <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie> cdlt:regionOf ?p1 }\n            WHERE { BIND(<https://data.lescheminsdelatransition.org/courses/voyage-inaugural-des-chemins-de-la-transition-a-velo> AS ?p1) }\n          ' },
  retryable: false
}
```

Il y a visiblement un problème avec cette requête SPARQL:

```sparql
  PREFIX cdlt: <http://virtual-assembly.org/ontologies/cdlt#>
  INSERT { <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie>, <https://data.lescheminsdelatransition.org/regions/occitanie> cdlt:regionOf ?p1 }
  WHERE { BIND(<https://data.lescheminsdelatransition.org/courses/voyage-inaugural-des-chemins-de-la-transition-a-velo> AS ?p1) }
```

**Comment by srosset81** [comment]
Corrigé a priori. Il fallait supprimer des duplicates (https://github.com/chemins-de-la-transition/semapps/commit/54c08dcc8adefca37417d340ec164b780ee11ea1)

**Comment by srosset81** [comment]
Il fallait aussi corriger la requête SPARQL :-) https://github.com/chemins-de-la-transition/semapps/commit/aa983679e617ddd6681994f248ca283999c1280e
Cette fois c'est bon !
