### ISSUE TITLE
 middleware: Error when creating secure dataset localData

### ISSUE THREAD

**Issue by ixxie** [chemins-de-la-transition/semapps#572]
An error appears in my middleware logs regarding the creation of a secure dataset `localData`:

```
middleware     | [2023-06-21T17:06:15.001Z] INFO  551565d5bcd7-31/TRIPLESTORE.DATASET: Dataset localData doesn't exist. Creating it...
middleware     | [2023-06-21T17:06:15.017Z] INFO  551565d5bcd7-31/TRIPLESTORE.DATASET:
middleware     | [2023-06-21T17:06:15.019Z] ERROR 551565d5bcd7-31/BROKER: Unable to start all services. Error: Error when creating secure dataset localData
middleware     |     at Service.create (/app/node_modules/@semapps/triplestore/subservices/dataset.js:60:17)
middleware     |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
middleware     |     at async Service.started (/app/services/triplestore.service.js:13:5)
middleware     |     at async Promise.all (index 37)
middleware     | [Runner] Error when creating secure dataset localData Error: Error when creating secure dataset localData
middleware     |     at Service.create (/app/node_modules/@semapps/triplestore/subservices/dataset.js:60:17)
middleware     |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
middleware     |     at async Service.started (/app/services/triplestore.service.js:13:5)
middleware     |     at async Promise.all (index 37)
```

The new [deployment README](https://github.com/chemins-de-la-transition/semapps/tree/master/deploy) which @srosset81 shared with me covers the setting of a variety of env vars, but replacing `localData` in `SEMAPPS_MAIN_DATASET` of `deploy/middleware/app/.env.local` was not mentioned.

**Comment by srosset81** [comment]
Usually it should work with the `localData` name, unless you already use it for another project.

The error message is not very clear so it's difficult to see what happened.

Did it end up working ?
